/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as ProgramIndexRouteImport } from './routes/program/index'
import { Route as ProgramBriliaRouteImport } from './routes/program/brilia'
import { Route as ProgramElsSchoolRouteImport } from './routes/program/els-school'
import { Route as ProgramJoytalkEnglishRouteImport } from './routes/program/joytalk-english'
import { Route as ProgramKidsproIdRouteImport } from './routes/program/kidspro-id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramBriliaRoute = ProgramBriliaRouteImport.update({
  id: '/program/brilia',
  path: '/program/brilia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramElsSchoolRoute = ProgramElsSchoolRouteImport.update({
  id: '/program/els-school',
  path: '/program/els-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramJoytalkEnglishRoute = ProgramJoytalkEnglishRouteImport.update({
  id: '/program/joytalk-english',
  path: '/program/joytalk-english',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKidsproIdRoute = ProgramKidsproIdRouteImport.update({
  id: '/program/kidspro-id',
  path: '/program/kidspro-id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/program/brilia': typeof ProgramBriliaRoute
  '/program/els-school': typeof ProgramElsSchoolRoute
  '/program/joytalk-english': typeof ProgramJoytalkEnglishRoute
  '/program/kidspro-id': typeof ProgramKidsproIdRoute
  '/program/': typeof ProgramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/program/brilia': typeof ProgramBriliaRoute
  '/program/els-school': typeof ProgramElsSchoolRoute
  '/program/joytalk-english': typeof ProgramJoytalkEnglishRoute
  '/program/kidspro-id': typeof ProgramKidsproIdRoute
  '/program': typeof ProgramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/program/brilia': typeof ProgramBriliaRoute
  '/program/els-school': typeof ProgramElsSchoolRoute
  '/program/joytalk-english': typeof ProgramJoytalkEnglishRoute
  '/program/kidspro-id': typeof ProgramKidsproIdRoute
  '/program/': typeof ProgramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/program/brilia'
    | '/program/els-school'
    | '/program/joytalk-english'
    | '/program/kidspro-id'
    | '/program/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/program/brilia'
    | '/program/els-school'
    | '/program/joytalk-english'
    | '/program/kidspro-id'
    | '/program'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/program/brilia'
    | '/program/els-school'
    | '/program/joytalk-english'
    | '/program/kidspro-id'
    | '/program/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KontakRoute: typeof KontakRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TentangKamiRoute: typeof TentangKamiRoute
  ProgramBriliaRoute: typeof ProgramBriliaRoute
  ProgramElsSchoolRoute: typeof ProgramElsSchoolRoute
  ProgramJoytalkEnglishRoute: typeof ProgramJoytalkEnglishRoute
  ProgramKidsproIdRoute: typeof ProgramKidsproIdRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/': {
      id: '/program/'
      path: '/program'
      fullPath: '/program/'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/brilia': {
      id: '/program/brilia'
      path: '/program/brilia'
      fullPath: '/program/brilia'
      preLoaderRoute: typeof ProgramBriliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/els-school': {
      id: '/program/els-school'
      path: '/program/els-school'
      fullPath: '/program/els-school'
      preLoaderRoute: typeof ProgramElsSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/joytalk-english': {
      id: '/program/joytalk-english'
      path: '/program/joytalk-english'
      fullPath: '/program/joytalk-english'
      preLoaderRoute: typeof ProgramJoytalkEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/kidspro-id': {
      id: '/program/kidspro-id'
      path: '/program/kidspro-id'
      fullPath: '/program/kidspro-id'
      preLoaderRoute: typeof ProgramKidsproIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KontakRoute: KontakRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TentangKamiRoute: TentangKamiRoute,
  ProgramBriliaRoute: ProgramBriliaRoute,
  ProgramElsSchoolRoute: ProgramElsSchoolRoute,
  ProgramJoytalkEnglishRoute: ProgramJoytalkEnglishRoute,
  ProgramKidsproIdRoute: ProgramKidsproIdRoute,
  ProgramIndexRoute: ProgramIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
